FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# TestAccount

The name of the API is "TestAccount", a test API for accounts

## Account [/account/{account_id}]

The API resource here is "account"

+ Parameters
    + account_id: `1234` (number, required) - ID of the account in the form of an integer
      
### View a Account Detail [GET]

A resource action, to get the details for a given account

+ Response 200 (application/json)

        [
            {
                "name": "my account",
                "number": "1237635673",
                "type": "simple"
            }
        ]